### PR TITLE
More fancy new stuff

### PR DESCRIPTION
**Pull request by Dormanil**
Look at the commits for more details on what changed

### CODE REVIEW

**Review by Tranberry — APPROVED** [review]
looks very well documented, I approve! :wink:

**Comment by Dormanil** [comment]
Still trying to get Travis to play nicely, so bear with me.

**Comment by Tranberry** [comment]
"All checks have failed" So brutal.

**Comment by Dormanil** [comment]
I give up. Someone else @vogonistic maybe, can try to fix travis.

**Pull request merged**
